Update repositories on disk on a fixed interval
RIPE-NCC/rpki-publication-server pull request #32
Opened 2021-03-24 16:41 UTC by bjpbakker

Replace on-demand writing of repository files with a fixed schedule. The
previous behavior caused publication messages to wait for FS updates, because
the `PublicationService` was used as lock target.

Rather than fixing the locking code, update the FS on a fixed interval. Checking
for changes in the database is quite cheap, and having a fixed schedule leads to
simpler code.

The interval is 10 seconds by default (in `reference.conf`) and can be adjusted
with `publication.server.repository-write-interval`.

2021-03-24 16:43 UTC, bjpbakker commented on src/main/scala/net/ripe/rpki/publicationserver/Boot.scala
> +           .flatMap(_ => system.terminate())
Note that the change here is `this.repositoryWriter.cancel()`. The changes on `Await.result ..` lines are correction of too much indentation.

2021-03-24 17:25 UTC, lolepezy requested changes

2021-03-24 17:25 UTC, lolepezy commented on src/main/scala/net/ripe/rpki/publicationserver/Boot.scala
> +    this.repositoryWriter = system.scheduler.scheduleAtFixedRate(
this one needs to start after dataFlusher.initFS() I believe. They in principle will lock on the DB, but it looks more reasonable to me to do 
```
Future { 
   dataFlusher.initFS(); 
   this.repositoryWriter = system.scheduler.scheduleAtFixedRate(.. no delay here.. )
   }
```

2021-03-24 17:25 UTC, lolepezy commented on src/main/scala/net/ripe/rpki/publicationserver/AppConfig.scala
> +  lazy val repositoryFlushInterval = getConfig.getDuration(
It would be nice to also remove the `snapshotSyncDelay`, this name makes more sense, but they are essentially the same values.

2021-03-24 17:25 UTC, lolepezy commented on src/main/resources/reference.conf
> +  server.repository-write-interval = 10s
Currently it's 120s in production. 
Generating 130mb file every 10 seconds consumes way too much space and keeps it busy.

2021-03-25 09:16 UTC, lolepezy commented on src/main/scala/net/ripe/rpki/publicationserver/Boot.scala
> +    this.repositoryWriter = system.scheduler.scheduleAtFixedRate(
Probably not ".. no delay here.." but the delay equal to the execution period.

2021-03-25 11:51 UTC, lolepezy approved these changes

2021-03-25 12:19 UTC, merged